/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Signer,
  utils,
  BigNumberish,
  Contract,
  ContractFactory,
  Overrides,
} from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  CrossChainGuard,
  CrossChainGuardInterface,
} from "../CrossChainGuard";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_ambBridge",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_ownerChainId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "ambBridge",
    outputs: [
      {
        internalType: "contract IAMB",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "isCalledByOwner",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ownerChainId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60e060405234801561001057600080fd5b5060405161039e38038061039e8339818101604052606081101561003357600080fd5b50805160208201516040909201516001600160601b0319606092831b8116608052911b1660c05260a05260805160601c60a05160c05160601c6102f86100a6600039806101bd528061027c52508061010e52806102a052508060b5528060e4528061012f52806101e752506102f86000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80630ba54df614610051578063270af851146100755780638da5cb5b14610091578063ff4d181514610099575b600080fd5b6100596100b3565b604080516001600160a01b039092168252519081900360200190f35b61007d6100d7565b604080519115158252519081900360200190f35b61005961027a565b6100a161029e565b60408051918252519081900360200190f35b7f000000000000000000000000000000000000000000000000000000000000000081565b6000336001600160a01b037f0000000000000000000000000000000000000000000000000000000000000000161480156101b457507f00000000000000000000000000000000000000000000000000000000000000007f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316639e307dff6040518163ffffffff1660e01b815260040160206040518083038186803b15801561018657600080fd5b505afa15801561019a573d6000803e3d6000fd5b505050506040513d60208110156101b057600080fd5b5051145b801561027557507f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03167f00000000000000000000000000000000000000000000000000000000000000006001600160a01b031663d67bdd256040518163ffffffff1660e01b815260040160206040518083038186803b15801561023e57600080fd5b505afa158015610252573d6000803e3d6000fd5b505050506040513d602081101561026857600080fd5b50516001600160a01b0316145b905090565b7f000000000000000000000000000000000000000000000000000000000000000081565b7f00000000000000000000000000000000000000000000000000000000000000008156fea2646970667358221220a96874825681466b352e5e294a7bdc7f6ade8860b6cf0d62f589d0816251fba764736f6c63430007060033";

export class CrossChainGuard__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _ambBridge: string,
    _ownerChainId: BigNumberish,
    _owner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<CrossChainGuard> {
    return super.deploy(
      _ambBridge,
      _ownerChainId,
      _owner,
      overrides || {}
    ) as Promise<CrossChainGuard>;
  }
  getDeployTransaction(
    _ambBridge: string,
    _ownerChainId: BigNumberish,
    _owner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(
      _ambBridge,
      _ownerChainId,
      _owner,
      overrides || {}
    );
  }
  attach(address: string): CrossChainGuard {
    return super.attach(address) as CrossChainGuard;
  }
  connect(signer: Signer): CrossChainGuard__factory {
    return super.connect(signer) as CrossChainGuard__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CrossChainGuardInterface {
    return new utils.Interface(_abi) as CrossChainGuardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CrossChainGuard {
    return new Contract(address, _abi, signerOrProvider) as CrossChainGuard;
  }
}
