/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAMB, IAMBInterface } from "../IAMB";

const _abi = [
  {
    inputs: [],
    name: "messageSender",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "messageSourceChainId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IAMB__factory {
  static readonly abi = _abi;
  static createInterface(): IAMBInterface {
    return new utils.Interface(_abi) as IAMBInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IAMB {
    return new Contract(address, _abi, signerOrProvider) as IAMB;
  }
}
