/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IOmnibridge, IOmnibridgeInterface } from "../IOmnibridge";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
      {
        internalType: "address",
        name: "_receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
    ],
    name: "relayTokens",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "_receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "relayTokensAndCall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IOmnibridge__factory {
  static readonly abi = _abi;
  static createInterface(): IOmnibridgeInterface {
    return new utils.Interface(_abi) as IOmnibridgeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOmnibridge {
    return new Contract(address, _abi, signerOrProvider) as IOmnibridge;
  }
}
